#!/usr/bin/env node
// The `test:states` lane: discover fixtures, build the harness page, serve it, run Playwright.
//
//   pnpm run test:states                       every fixture, four projects, two themes
//   pnpm run test:states -- --grep Button      Playwright filters pass through (a leading
//   pnpm run test:states -- --project webkit   `--` is dropped)
//   pnpm run test:states -- --skip-build       reuse the last harness build
//
// Output (gitignored): states/.output/screenshots/<Subject>/<state>-<engine>-<theme>.png and
// states/.output/gallery.html. The tracked states/coverage.json is regenerated on every run.

import { spawn } from "node:child_process";
import { existsSync, mkdirSync, readdirSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join, relative } from "node:path";
import {
  DiscoveryError,
  OUTPUT_ROOT,
  STATES_ROOT,
  UI_ROOT,
  discover,
  writeOutputs,
} from "./discover.mjs";
import { startServer } from "./serve.mjs";

const require = createRequire(import.meta.url);
const SITE_ROOT = join(OUTPUT_ROOT, "site");
const SCREENSHOT_ROOT = join(OUTPUT_ROOT, "screenshots");
const RUNNER_FLAGS = new Set(["--skip-build"]);

export function harnessViteConfig(react) {
  return {
    configFile: false,
    root: join(STATES_ROOT, "app"),
    base: "./",
    mode: "development",
    logLevel: "warn",
    plugins: [react()],
    // React's development build, so its own warnings reach the console and fail the fixture.
    define: { "process.env.NODE_ENV": JSON.stringify("development") },
    resolve: { dedupe: ["react", "react-dom"] },
    css: {
      modules: { localsConvention: "camelCase" },
      preprocessorOptions: { scss: { api: "modern-compiler" } },
    },
    build: {
      outDir: SITE_ROOT,
      emptyOutDir: true,
      minify: false,
      sourcemap: false,
      target: "es2022",
      reportCompressedSize: false,
      chunkSizeWarningLimit: 100_000,
    },
  };
}

async function buildHarness() {
  process.env.NODE_ENV = "development";
  const { build } = await import("vite");
  const { default: react } = await import("@vitejs/plugin-react");
  const started = Date.now();
  await build(harnessViteConfig(react));
  console.log(`Harness built in ${((Date.now() - started) / 1000).toFixed(1)}s.`);
}

function runPlaywright(args, env) {
  const cli = join(dirname(require.resolve("@playwright/test/package.json")), "cli.js");
  return new Promise((resolve) => {
    const child = spawn(
      process.execPath,
      [cli, "test", "-c", join(STATES_ROOT, "playwright.config.ts"), ...args],
      { cwd: UI_ROOT, stdio: "inherit", env: { ...process.env, ...env } }
    );
    child.on("exit", (code, signal) => resolve(signal ? 1 : (code ?? 1)));
  });
}

function escapeHtml(value) {
  return value.replace(
    /[&<>"]/g,
    (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[c]
  );
}

/** A static page of every screenshot on disk for a known fixture, grouped by subject and state. */
export function writeGallery(fixtures) {
  const sections = [];
  const subjects = [...new Set(fixtures.map((fixture) => fixture.subject))].sort();
  for (const subject of subjects) {
    const dir = join(SCREENSHOT_ROOT, subject);
    if (!existsSync(dir)) continue;
    const files = readdirSync(dir)
      .filter((name) => name.endsWith(".png"))
      .sort();
    const states = fixtures.filter((fixture) => fixture.subject === subject);
    const rows = [];
    for (const { state } of states) {
      const shots = files.filter((name) => name.startsWith(`${state}-`));
      if (shots.length === 0) continue;
      const figures = shots
        .map((name) => {
          const src = escapeHtml(relative(OUTPUT_ROOT, join(dir, name)));
          const label = escapeHtml(name.replace(/\.png$/, ""));
          return `<figure><img src="${src}" alt="${label}" loading="lazy"><figcaption>${label}</figcaption></figure>`;
        })
        .join("\n");
      rows.push(`<h3>${escapeHtml(state)}</h3>\n<div class="shots">${figures}</div>`);
    }
    if (rows.length > 0)
      sections.push(`<section><h2>${escapeHtml(subject)}</h2>\n${rows.join("\n")}</section>`);
  }
  const html = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><title>State fixtures</title>
<style>
body { font: 14px/1.4 system-ui, sans-serif; margin: 24px; color: #1c1c1c; background: #f6f6f4; }
h2 { margin-top: 40px; } h3 { margin: 20px 0 8px; font-weight: 600; }
.shots { display: flex; flex-wrap: wrap; gap: 12px; align-items: flex-start; }
figure { margin: 0; background: #fff; border: 1px solid #ddd; padding: 8px; }
img { display: block; max-width: 420px; height: auto; }
figcaption { margin-top: 6px; font-size: 12px; color: #555; }
</style></head><body>
<h1>State fixtures</h1>
<p>Generated by states/run.mjs. Names are &lt;state&gt;-&lt;engine&gt;-&lt;theme&gt;.</p>
${sections.join("\n") || "<p>No screenshots yet.</p>"}
</body></html>
`;
  writeFileSync(join(OUTPUT_ROOT, "gallery.html"), html);
}

async function main(argv) {
  const args = argv[0] === "--" ? argv.slice(1) : argv;
  const skipBuild = args.includes("--skip-build");
  const playwrightArgs = args.filter((arg) => !RUNNER_FLAGS.has(arg));

  const result = discover();
  writeOutputs(result);
  const { summary } = result.coverage;
  console.log(
    `${result.fixtures.length} fixtures; ${summary.withFixtures}/${summary.components} components ` +
      `have fixtures (columns: ${summary.covered} covered, ${summary.na} n/a, ${summary.missing} missing).`
  );

  if (!skipBuild || !existsSync(join(SITE_ROOT, "index.html"))) await buildHarness();
  mkdirSync(SCREENSHOT_ROOT, { recursive: true });

  const server = await startServer(SITE_ROOT);
  let code = 1;
  try {
    code = await runPlaywright(playwrightArgs, { STATES_BASE_URL: server.url });
  } finally {
    await server.close();
  }
  writeGallery(result.fixtures);
  console.log(
    `Screenshots: ${relative(UI_ROOT, SCREENSHOT_ROOT)}/  Gallery: ${relative(UI_ROOT, join(OUTPUT_ROOT, "gallery.html"))}`
  );
  return code;
}

main(process.argv.slice(2))
  .then((code) => {
    process.exitCode = code;
  })
  .catch((error) => {
    console.error(error instanceof DiscoveryError ? error.message : error);
    process.exitCode = 1;
  });
